### PR TITLE
Added videos

### PR DESCRIPTION
**Pull request by fikovnik**

### CODE REVIEW

**Comment by heathermiller** [comment]
oh.my.god. I'm doing this concurrently... Glad you finished it (I was partway through). Thanks!

**Comment by heathermiller** [comment]
I'm renaming all the videos over on YouTube now then so they match last year's naming scheme.

**Comment by fikovnik** [comment]
Sorry, I should have asked ... I only spoke to Jan.

Can you also update the background on the youtube channel?

**Comment by heathermiller** [comment]
Yeah, doing that. No worries.

**Pull request merged**
