### PR TITLE
WIP: 2017 version

### PR DESCRIPTION
**Pull request by jakubzitny**
This MR
- adds new files for 2017 version of the website
- fixes links and dates
- changes redirect to the new 2017 version

TODOs
- [ ] change dates in deadlines
- [ ] add speaker info to `2017/speakers` and `_includes/2017-main-content.html`
- [x] remove the `Sold out` part
- [x] add new splash background for Barcelona
- [ ] more? (cc @heathermiller)

### CODE REVIEW

**Comment by heathermiller** [comment]
<3 thank you @jakubzitny, you have no idea...

**Comment by heathermiller** [comment]
What about this image for the background? http://2015.phpconference.es/wp-content/uploads/2015/05/barcelona1.jpg

**Comment by heathermiller** [comment]
(I can get around to making the colors match the image in a day or two)

**Comment by ulysses4ever** [comment]
Not sure that it is a good idea to reuse previous conferences' splash screens. Seems that Google have more. I'd bet for [this one](https://static1.squarespace.com/static/52da9677e4b03d314575985a/t/5668a2cbd82d5e5a433e8d16/1449697996647/Barcelona+Best+Hotels.jpg?format=1500w).

Do we know dates?

How do we handle "Not promised a keynote" / "Keynote" (shall we omit first ones until some info gets in?).

**Comment by jakubzitny** [comment]
@ulysses4ever not really a good quality that one. Btw I've invited you to my fork, you can push to this branch and the commits will appear here.

**Comment by ulysses4ever** [comment]
My bad. Thanks!

**Comment by heathermiller** [comment]
Would you mind if we just used the image I linked to for the backdrop? As mentioned, I usually develop color schemes for these that match the picture, and this one has a nice base set of colors that would work nicely for the site color scheme.

(All promo photos of Barcelona have probably already been used for conferences btw. And posters, advertisements, etc. So just because a photo has been used for a conference before doesn't mean we should avoid it or anything.)

**Comment by ulysses4ever** [comment]
@heathermiller ok

**Comment by jakubzitny** [comment]
Ok, I've added the background. I tried to move it around a bit because the logo was just in front of the cathedral. The chices are as folows. I chose the second one for now:

screen shot 2017-03-07 at 00 09 18
screen shot 2017-03-07 at 00 12 35

As you can see I still wasn't able to get the fonts working. Will try tomorrow.

I also removed the `Sold out` part. Is there going to be any "Early registration" date?

**Comment by fikovnik** [comment]
I will add the speakers we have so far.

**Comment by fikovnik** [comment]
@jakubzitny - the fonts work fine you should just access the site as http://localhost:4000/ rather than http://127.0.0.1/ I updated the `_config.yml`

**Comment by heathermiller** [comment]
Don't worry about the fonts. They'll work as soon as they're merged :)

**Comment by heathermiller** [comment]
> @jakubzitny - the fonts work fine you should just access the site as http://localhost:4000/ rather than http://127.0.0.1/ I updated the _config.yml

Or that too 😉

**Comment by heathermiller** [comment]
Hey guys, I'm merging this just to make it easier to work on 🙂 
Thanks everybody for all of your help!

**Pull request merged**
