### PR TITLE
Program draft

### PR DESCRIPTION
**Pull request by fikovnik**
Missing:

- [ ] John Hughes's talk info
- [ ] Julien Verlaguet's talk info
- [ ] room names
- [ ] update / remove tags at keynotes

Minor:

- [ ] last year promoted speakers had their names pointing to their websites, this year they point to the corresponding talk pages, shall their websites link be used anywhere?
- [ ] twitter accounts are not shown in the program - should they be shown?

### CODE REVIEW

**Comment by heathermiller** [comment]
Gah, conflicts

**Comment by fikovnik** [comment]
You can ignore them, you can use the version from this PR or I can I create a new PR.

Or better - I just resolved them.

**Comment by heathermiller** [comment]
LOOKS GREAT! You even caught and changed the "two days, two tracks" thing to "two days, three tracks" ❤️ 

Thanks a ton

**Comment by fikovnik** [comment]
I wish I did, but that was you actually :-)

btw: there are still missing the talks of
- John Hughes
- Julien Verlaguet

Right now they are rendered as "John Hughes" and "Julien Verlaguet".

**Comment by heathermiller** [comment]
Yep, I saw. I'll dig around in my email to see if I can find something from Julien. I'm pretty sure though that John hasn't given us an abstract yet... We'll have to get back to pinging him.

**Pull request merged**
